# display dimensions
WIDTH, HEIGHT = 600, 400

# stick properties
STICK_WIDTH, STICK_HEIGHT = 10, 50
STICK_WIDTH_SPACE, STICK_HEIGHT_SPACE = 50, 75

# button properties
BUTTON_WIDTH, BUTTON_HEIGHT = 50, 50
